export const SYSTEM_PERMISSIONS = {
  SYSTEM_USER_LIST: "system:user:list",
  SYSTEM_PERMISSION_LIST: "system:permission:list",
  SYSTEM_PERMISSION_CREATE: "system:permission:create",
  SYSTEM_PERMISSION_UPDATE: "system:permission:update",
  SYSTEM_ADMIN_PERMISSION_VIEW: "system:admin-permission:view",
  SYSTEM_ADMIN_PERMISSION_UPDATE: "system:admin-permission:update",
  SYSTEM_PERMISSION_RULE_LIST: "system:permission-rule:list",
  SYSTEM_PERMISSION_RULE_CREATE: "system:permission-rule:create",
  SYSTEM_PERMISSION_RULE_UPDATE: "system:permission-rule:update",
  SYSTEM_PERMISSION_RULE_DELETE: "system:permission-rule:delete",
  SYSTEM_PERMISSION_RULE_APPLY: "system:permission-rule:apply",
} as const;

export const SYSTEM_PERMISSION_SEEDS = [
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_USER_LIST,
    name: "用户列表",
    type: "api",
    description: "查看管理端用户列表",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_LIST,
    name: "权限列表",
    type: "api",
    description: "查看权限点定义列表",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_CREATE,
    name: "新增权限",
    type: "api",
    description: "新增权限点定义",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_UPDATE,
    name: "修改权限",
    type: "api",
    description: "修改权限点定义",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_ADMIN_PERMISSION_VIEW,
    name: "查看管理员权限",
    type: "api",
    description: "查看管理员权限配置和最终生效权限",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_ADMIN_PERMISSION_UPDATE,
    name: "修改管理员权限",
    type: "api",
    description: "修改管理员权限配置",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_RULE_LIST,
    name: "权限规则列表",
    type: "api",
    description: "查看权限规则列表",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_RULE_CREATE,
    name: "创建权限规则",
    type: "api",
    description: "创建权限规则",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_RULE_UPDATE,
    name: "修改权限规则",
    type: "api",
    description: "修改权限规则",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_RULE_DELETE,
    name: "删除权限规则",
    type: "api",
    description: "删除权限规则",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
  {
    code: SYSTEM_PERMISSIONS.SYSTEM_PERMISSION_RULE_APPLY,
    name: "套用权限规则",
    type: "api",
    description: "给管理员套用权限规则",
    scope: "system",
    is_bind: false,
    is_bind_id: null,
  },
] as const;
